---
- name: PHP | Add ppa Repository
  sudo: yes
  apt_repository:
    repo: "ppa:ondrej/{{ php_ppa }}"
    update_cache: yes
    state: present
  when: php_ppa is defined and not (php_ppa is none or php_ppa | trim == '')

- name: PHP | Install php5 fpm and cli
  sudo: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items:
    - php5-cli
    - php5-fpm
  notify: restart php5-fpm

- name: PHP | Install PHP Packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items: php_packages

- name: PHP | Install dev PHP Packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items: php_dev_packages
  when: not ansidev_production

- name: PHP | Install production PHP Packages
  sudo: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items: php_production_packages
  when: ansidev_production

- name: PHP | Install xDebug
  sudo: yes
  apt:
    pkg: php5-xdebug
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  when: php_xdebug

- include: configure.yml
