---
- name: PHP | Set permissions on socket - owner
  sudo: yes
  lineinfile:
    dest: "{{ php_fpm_path }}/pool.d/www.conf"
    regexp: "^;?listen.owner"
    line: listen.owner = www-data
    state: present
  notify: restart php5-fpm

- name: PHP | Set permissions on socket - group
  sudo: yes
  lineinfile:
    dest: "{{ php_fpm_path }}/pool.d/www.conf"
    regexp: "^;?listen.group"
    line: listen.group = www-data
    state: present
  notify: restart php5-fpm

- name: PHP | Set permissions on socket - mode
  sudo: yes
  lineinfile:
    dest: "{{ php_fpm_path }}/pool.d/www.conf"
    regexp: "^;?listen.mode"
    line: listen.mode = 0660
    state: present
  notify: restart php5-fpm

- name: PHP | Ensure timezone is set in fpm php.ini
  sudo: yes
  lineinfile:
    dest: "{{ php_fpm_path }}/php.ini"
    regexp: "^;?date.timezone"
    line: date.timezone = {{ php_date_timezone }}
    state: present
  notify: restart php5-fpm

- name: PHP | Disable fix_pathinfo for php .ini files
  sudo: yes
  lineinfile:
    dest: "{{ php_fpm_path }}/php.ini"
    regexp: "^;?cgi.fix_pathinfo"
    line: cgi.fix_pathinfo=0
    state: present
  notify: restart php5-fpm

- name: PHP | Set max upload filesize
  sudo: yes
  lineinfile:
    dest: "{{ php_fpm_path }}/php.ini"
    regexp: "^;?upload_max_filesize"
    line: "upload_max_filesize = {{ php_max_file_upload }}"
    state: present
  notify: restart php5-fpm

- name: PHP | Set max post size
  sudo: yes
  lineinfile:
    dest: "{{ php_fpm_path }}/php.ini"
    regexp: "^;?post_max_size"
    line: "post_max_size = {{ php_max_body_size }}"
    state: present
  notify: restart php5-fpm
